AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  ECS Fargate service with ALB and Application Auto Scaling (CPU based).
  This template expects you to pass networking (VpcId, SubnetIds, SecurityGroupIds)
  and the container ImageUri to run. It will create an ECS cluster, task
  definition, service, ALB, and an autoscaling policy based on CPU.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC where resources will be created (use default or your VPC)

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for the ALB and Fargate tasks (use at least 2 private/public subnets)

  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security groups for the ALB (and tasks if desired). ALB must allow inbound HTTP/80.

  ImageUri:
    Type: String
    Description: Full ECR image URI including tag (e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest)

  ContainerPort:
    Type: Number
    Default: 8000
    Description: Port the container listens on

  DesiredCount:
    Type: Number
    Default: 1

  MinCapacity:
    Type: Number
    Default: 1

  MaxCapacity:
    Type: Number
    Default: 4

  TargetCPUUtilization:
    Type: Number
    Default: 50
    Description: Target average CPU utilization (%) for scaling

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties: {}

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: cloudlab-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: cloudlab-container
          Image: !Ref ImageUri
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: cloudlab

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets: !Ref SubnetIds
      SecurityGroups: !Ref SecurityGroupIds

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port: 80
      Protocol: HTTP
      LoadBalancerArn: !Ref LoadBalancer
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole

  ECSService:
    Type: AWS::ECS::Service
    DependsOn: Listener
    Properties:
      # Make the service name predictable so the ApplicationAutoScaling ResourceId
      # can reference it (service/<Cluster>/<StackName>-service)
      ServiceName: !Sub "${AWS::StackName}-service"
      Cluster: !Ref ECSCluster
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups: !Ref SecurityGroupIds
      LoadBalancers:
        - ContainerName: cloudlab-container
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup
      Role: !GetAtt ECSServiceRole.Arn

  ServiceScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: ECSService
    Properties:
      MaxCapacity: !Ref MaxCapacity
      MinCapacity: !Ref MinCapacity
      ResourceId: !Sub "service/${ECSCluster}/${AWS::StackName}-service"
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ServiceScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ServiceScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: !Ref TargetCPUUtilization
        ScaleInCooldown: 60
        ScaleOutCooldown: 60

Outputs:
  LoadBalancerDNS:
    Description: DNS name of the ALB
    Value: !GetAtt LoadBalancer.DNSName

  ClusterName:
    Description: ECS Cluster name
    Value: !Ref ECSCluster

  ServiceName:
    Description: ECS Service
    Value: !Ref ECSService
